### ISSUE TITLE
Array type specifiers in method declarations are not rendered

### ISSUE THREAD

**Issue by thecatalinstan** [kontaktio/appledoc-template#1] opened 2018-06-20 10:28 UTC
When declaring methods or functions that use the _modern_ objective-c array/dictionary type specifier  s (`NSArray<NSString *> *` and similar), the type specifier is not rendered in the resulting html. Thus:

```objective-c
- (NSArray<NSString *> *)doSomeStuffWithThis:(NSDictionary<NSString *, NSNumber *> *)input error:(NSError * __autoreleasing *)error;
```

is documented as 

```objective-c
- (NSArray *)doSomeStuffWithThis:(NSDictionary *)input 
                           error:(NSError * __autoreleasing *)error;
```

**Comment by stoprocent** [comment] 2018-07-20 13:05
This is such an old template I'm not really maintaining it. If you want I'm happy to merge your changes tho. I will be switching to `jazzy` soon so I'm not crazy about updating this template :)

Duplicate of #3

**Closed by stoprocent** 2018-07-20 13:05 UTC
